# example docker-compose.yaml
version: "3.7"

services:
  fourget:
    build: .
    restart: unless-stopped
    environment:
      - FOURGET_PROTO=http
      - FOURGET_SERVER_NAME=Sorvx Search
      - FOURGET_INSTANCES=https://4get.ca

    ports:
      - "113:113"
      - "441:441"
    # volumes:
    # - /etc/letsencrypt/live/domain.tld:/etc/4get/certs # mount ssl
    # - ./banner:/var/www/html/4get/banner # mount custom banners
    # - ./data/captcha:/var/www/html/4get/data/captcha # mount captcha images
